-- Migraciones para RQ de almacén y RQ por compras
-- Cabecera de RQ
CREATE TABLE IF NOT EXISTS rq_headers (
    CODE VARCHAR(64) PRIMARY KEY,
    TYPE ENUM('warehouse','purchase') NOT NULL,
    ORDER_CODE VARCHAR(64) NOT NULL,
    REQUESTER VARCHAR(191) NOT NULL,
    NOTES TEXT,
    STATE ENUM('pending','approved','attended','rejected') NOT NULL DEFAULT 'pending',
    APPROVED_BY VARCHAR(191),
    ATTENDED_BY VARCHAR(191),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- Detalle de RQ
CREATE TABLE IF NOT EXISTS rq_items (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    RQ_CODE VARCHAR(64) NOT NULL,
    SKU VARCHAR(128) NOT NULL,
    DESCRIPTION VARCHAR(255) NOT NULL,
    QTY DECIMAL(12,2) NOT NULL,
    UNIT_COST DECIMAL(12,2) DEFAULT 0,
    SOURCE ENUM('warehouse','purchase') NOT NULL,
    FOREIGN KEY (RQ_CODE) REFERENCES rq_headers(CODE) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- Historial de estados por RQ
CREATE TABLE IF NOT EXISTS rq_status_history (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    RQ_CODE VARCHAR(64) NOT NULL,
    STATE ENUM('pending','approved','attended','rejected') NOT NULL,
    COMMENT TEXT,
    CHANGED_BY VARCHAR(191) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (RQ_CODE) REFERENCES rq_headers(CODE) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- Salidas de inventario vinculadas a RQ de almacén
CREATE TABLE IF NOT EXISTS inventory_movements (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    RQ_CODE VARCHAR(64) NOT NULL,
    SKU VARCHAR(128) NOT NULL,
    QTY DECIMAL(12,2) NOT NULL,
    UNIT_COST DECIMAL(12,2) NOT NULL,
    ORDER_CODE VARCHAR(64) NOT NULL,
    MOVEMENT_TYPE ENUM('out','in') NOT NULL DEFAULT 'out',
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (RQ_CODE) REFERENCES rq_headers(CODE) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- Impacto de costos en Orden de Trabajo por RQ atendidas
CREATE TABLE IF NOT EXISTS order_cost_impacts (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    ORDER_CODE VARCHAR(64) NOT NULL,
    RQ_CODE VARCHAR(64) NOT NULL,
    TOTAL_COST DECIMAL(12,2) NOT NULL,
    NOTES TEXT,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (RQ_CODE) REFERENCES rq_headers(CODE) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
