-- Auditoría de ajustes de costo y campos de conteo físico

-- Asegurar columnas de conteo físico
ALTER TABLE inve ADD COLUMN IF NOT EXISTS REAL_AMOUNT DECIMAL(18,4) NOT NULL DEFAULT 0;
ALTER TABLE inve ADD COLUMN IF NOT EXISTS PHYSICAL_COUNT DECIMAL(18,4) NOT NULL DEFAULT 0;
ALTER TABLE inve ADD COLUMN IF NOT EXISTS VARIANCE DECIMAL(18,4) NOT NULL DEFAULT 0;

-- Tabla de auditoría de costos
CREATE TABLE IF NOT EXISTS inve_cost_audit (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    ITEM_CODE VARCHAR(64) NOT NULL,
    COSTO_ANTERIOR DECIMAL(18,4) NOT NULL,
    COSTO_NUEVO DECIMAL(18,4) NOT NULL,
    USUARIO VARCHAR(64) NOT NULL,
    OBSERVACIONES TEXT,
    FECHA DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_inve_cost_item ON inve_cost_audit (ITEM_CODE);
CREATE INDEX IF NOT EXISTS idx_inve_cost_user ON inve_cost_audit (USUARIO);
