-- Esquema para gestión de cotizaciones y catálogo comercial

CREATE TABLE IF NOT EXISTS catalog_items (
    CODE VARCHAR(64) PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    TYPE ENUM('item','servicio') NOT NULL DEFAULT 'item',
    INVENTORY_CODE VARCHAR(64) NULL,
    UNIT VARCHAR(64) DEFAULT 'UND',
    DEFAULT_PRICE DECIMAL(14,2) DEFAULT 0,
    STATUS TINYINT(1) DEFAULT 1,
    UPDATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS quotes (
    CODE VARCHAR(64) PRIMARY KEY,
    DATE DATETIME NOT NULL,
    CLIENTCODE VARCHAR(64) NOT NULL,
    CLIENTNAME VARCHAR(255) NOT NULL,
    SUCUCODE VARCHAR(64) NULL,
    SUCUNAME VARCHAR(255) NULL,
    CONTACT VARCHAR(255) NULL,
    VALIDUNTIL DATE NULL,
    STATUS ENUM('draft','sent','approved','rejected') DEFAULT 'draft',
    TOTAL DECIMAL(14,2) DEFAULT 0,
    CURRENCY VARCHAR(8) DEFAULT 'COP',
    NOTES TEXT NULL,
    CREATEDBY VARCHAR(255) NOT NULL,
    CREATEDBYCODE VARCHAR(64) NOT NULL,
    APPROVED_AT DATETIME NULL,
    SENT_AT DATETIME NULL,
    ORDERCODE VARCHAR(64) NULL,
    INTERNAL_COST_TOTAL DECIMAL(14,2) DEFAULT 0,
    UPDATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS quote_items (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    QUOTE_CODE VARCHAR(64) NOT NULL,
    ITEM_CODE VARCHAR(64) NOT NULL,
    ITEM_DESC VARCHAR(255) NOT NULL,
    ITEM_TYPE ENUM('item','servicio') DEFAULT 'item',
    QTY DECIMAL(12,2) DEFAULT 1,
    UNIT_PRICE DECIMAL(14,2) DEFAULT 0,
    TAX DECIMAL(5,2) DEFAULT 0,
    TOTAL DECIMAL(14,2) DEFAULT 0,
    INVENTORY_CODE VARCHAR(64) NULL,
    FOREIGN KEY (QUOTE_CODE) REFERENCES quotes(CODE)
);

CREATE TABLE IF NOT EXISTS quote_status_history (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    QUOTE_CODE VARCHAR(64) NOT NULL,
    STATUS ENUM('draft','sent','approved','rejected') NOT NULL,
    COMMENT TEXT NULL,
    CHANGED_BY VARCHAR(255) NOT NULL,
    CHANGED_BY_CODE VARCHAR(64) NOT NULL,
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (QUOTE_CODE) REFERENCES quotes(CODE)
);

CREATE TABLE IF NOT EXISTS quote_internal_costs (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    QUOTE_CODE VARCHAR(64) NOT NULL,
    COST_TYPE VARCHAR(128) NOT NULL,
    AMOUNT DECIMAL(14,2) DEFAULT 0,
    NOTE TEXT NULL,
    FOREIGN KEY (QUOTE_CODE) REFERENCES quotes(CODE)
);

-- Relación opcional con órdenes de trabajo existentes
ALTER TABLE orders ADD COLUMN IF NOT EXISTS QUOTECODE VARCHAR(64) NULL;
CREATE INDEX IF NOT EXISTS idx_orders_quote ON orders(QUOTECODE);
