<?php
return [
    'role_permissions' => [
        'A' => ['*'],
        'CO' => [
            'inventory.view',
            'inventory.create',
            'inventory.edit',
            'inventory.movement',
            'inventory.adjustment',
            'purchases.orders',
            'costSheets.manage',
            'internalSheets.view',
            'internalSheets.manage',
            'reports.export',
        ],
        'JZ' => [
            'inventory.view',
            'costSheets.manage',
            'internalSheets.view',
            'reports.export',
        ],
        'T' => [
            'internalSheets.view',
        ],
        'C' => [
            'inventory.view',
        ],
    ],
    'method_permissions' => [
        'users' => [
            'getInveList' => 'inventory.view',
            'inveSave' => ['inventory.create', 'inventory.edit'],
            'addInvQty' => 'inventory.movement',
            'discountInv' => ['inventory.movement', 'inventory.adjustment'],
            'saveoPart' => 'costSheets.manage',
            'saveoOther' => 'costSheets.manage',
            'saveoOtherLeg' => 'costSheets.manage',
            'updateActCost' => 'costSheets.manage',
            'updatePartCost' => 'costSheets.manage',
            'updateOtherCost' => 'costSheets.manage',
            'getOtotals' => 'costSheets.manage',
            'orderSave' => 'costSheets.manage',
            'reportCreate' => 'costSheets.manage',
            'reportCreateTotalized' => 'costSheets.manage',
            'generateRecepit' => 'purchases.orders',
            'nullifyReceipt' => 'purchases.orders',
            'redateReceipt' => 'purchases.orders',
            'setResolution' => 'purchases.orders',
            'getLeg' => 'internalSheets.view',
            'getUserLegs' => 'internalSheets.view',
            'refreshLegCodes' => 'internalSheets.manage',
            'restoreLeg' => 'internalSheets.manage',
            'exportCVS' => 'reports.export',
        ],
        'inventory' => [
            'listItems' => 'inventory.view',
            'saveItem' => ['inventory.create', 'inventory.edit'],
            'registerEntry' => 'inventory.movement',
            'registerExit' => ['inventory.movement', 'inventory.adjustment'],
            'listMovements' => 'inventory.view',
        ],
        'purchases' => [
            'createSupplier' => 'purchases.orders',
            'listSuppliers' => 'purchases.orders',
            'createPoFromRq' => 'purchases.orders',
            'updateNegotiatedCosts' => 'purchases.orders',
            'listPurchaseOrders' => 'purchases.orders',
            'receivePurchase' => 'purchases.orders',
        ],
    ],
];
